# This workflow will get the latest tag and bump the version.
# The version defaults to #minor unless #major or #patch are found in any commit message.

name: Bump version
on:
  push:
    branches:
      - master
      - develop

  workflow_dispatch:

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        token: '${{ secrets.PERSONAL_TOKEN }}'

    - name: Bump version and push tag
      uses: fermoya/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        TAG_CONTEXT: branch
        DEFAULT_BUMP: none
        WITH_V: false
        PRERELEASE_SUFFIX: beta
