# This workflow will rebase legacy-projects branch on new pushes to master

name: Rebase branch legacy-projects

on:
  # Trigger the workflow on push pull request or manually
  push: 
    branches: [ develop ]

  workflow_dispatch:

jobs:
  rebase:
    name: Checkout legacy-projects and rebase
    runs-on: ubuntu-latest
    steps:          
      - name: Automatic Rebase
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          USER_NAME: fermoya
          USER_EMAIL: fmdr.ct@gmail.com
          OUTDATED_BRANCH: legacy-projects
          BASE_BRANCH: develop
        run: |
          FOLDER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)

          git clone https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          cd $FOLDER
          git checkout $OUTDATED_BRANCH

          echo Adding origin as $GITHUB_REPOSITORY
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"

          git fetch origin $BASE_BRANCH

          echo git pull --rebase origin $OUTDATED_BRANCH
          git pull --rebase origin $OUTDATED_BRANCH

          echo Rebasing $BASE_BRANCH onto $OUTDATED_BRANCH
          echo git rebase origin/$BASE_BRANCH
          git rebase origin/$BASE_BRANCH

          echo git push --force-with-lease origin $OUTDATED_BRANCH
          git push --force-with-lease origin $OUTDATED_BRANCH

          cd ..
          rm -rf $FOLDER
