# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/
version: 2.1

workflows:
  version: 2
  default:
    jobs:
      - build:
          matrix:
            parameters:
              xcode: ["11.7.0", "12.0.0"]
          filters:
            tags:
              only: /.*/

jobs:
  build:
    parameters:
      xcode:
        type: string
    macos:
      xcode: << parameters.xcode >>
    steps:
      - checkout
      - run:
          name: Unzip bundled Cedar
          command: |
            pushd Carthage/Build/iOS
            unzip -u Cedar.framework.zip
            popd
      - run:
          name: Test
          command: xcodebuild -project MapboxMobileEventsTests.xcodeproj -scheme MMETestHost build test -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
      - run:
          name: Test CocoaPods
          command: Tests/Integration/test_cocoapods.sh
      - run:
          name: Test Carthage
          command: Tests/Integration/test_carthage.sh
